/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        "nunito-sans": ["Nunito Sans", "sans-serif"],
      },
      fontSize: {
        h1: ["60px", { lineHeight: "72px", fontWeight: "bold" }],
        h2: ["48px", { lineHeight: "58px", fontWeight: "bold" }],
        h3: ["40px", { lineHeight: "48px", fontWeight: "bold" }],
        h4: ["30px", { lineHeight: "38px", fontWeight: "bold" }],
        h5: ["28px", { lineHeight: "40px", fontWeight: "semibold" }],
        h6: ["24px", { lineHeight: "30px", fontWeight: "semibold" }],

        "body-large-regular": [
          "18px",
          { lineHeight: "26px", fontWeight: "regular" },
        ],
        "body-large-medium": [
          "18px",
          { lineHeight: "26px", fontWeight: "medium" },
        ],
        "body-large-semibold": [
          "18px",
          { lineHeight: "26px", fontWeight: "semibold" },
        ],
        "body-large-bold": ["18px", { lineHeight: "26px", fontWeight: "bold" }],

        "body-medium-regular": [
          "16px",
          { lineHeight: "24px", fontWeight: "regular" },
        ],
        "body-medium-medium": [
          "16px",
          { lineHeight: "24px", fontWeight: "medium" },
        ],
        "body-medium-semibold": [
          "16px",
          { lineHeight: "24px", fontWeight: "semibold" },
        ],
        "body-medium-bold": [
          "16px",
          { lineHeight: "24px", fontWeight: "bold" },
        ],

        "body-small-regular": [
          "14px",
          { lineHeight: "22px", fontWeight: "regular" },
        ],
        "body-small-medium": [
          "14px",
          { lineHeight: "22px", fontWeight: "medium" },
        ],

        "body-extra-small-regular": [
          "12px",
          { lineHeight: "20px", fontWeight: "regular" },
        ],
        "body-extra-small-medium": [
          "12px",
          { lineHeight: "20px", fontWeight: "medium" },
        ],
      },
      colors: {
        alert: {
          success: {
            50: "#DFF8EC",
            100: "#B2ECD0",
            300: "#15D293",
            500: "#00BC65",
            700: "#00994D",
            900: "#00672B",
          },
          warning: {
            50: "#FDF8E1",
            100: "#FBEBB4",
            300: "#F7D352",
            500: "#F5BF17",
            700: "#F59F0B",
            900: "#F47103",
          },
          error: {
            50: "#FFEAED",
            100: "#FFC9CE",
            300: "#E6696A",
            500: "#F32E26",
            700: "#D31121",
            900: "#B7000C",
          },
        },
        dark: {
          50: "#E5E7EB",
          100: "#BEC5CC",
          300: "#959EA9",
          500: "#6D7988",
          700: "#526071",
          900: "#000211",
          950: "#111B26",
          800: "#1F2B39",
          600: "#2C3C4D",
          400: "#37485B",
          200: "#6D7988",
        },
        primary: {
          DEFAULT: "#3758F9",
          50: "#E3F2FF",
          100: "#BBDFFF",
          200: "#93CBFC",
          300: "#5FB7FF",
          400: "#4AA7F9",
          500: "#0099FF",
          600: "#2D8BE9",
          700: "#2879D6",
          800: "#2469C4",
          900: "#1C4AA5",
        },
        secondary: "#13C296",
        "primary-text": "#637381",
        "secondary-text": "#8899A8",
        stroke: "#DFE4EA",
        gray: {
          1: "#F9FAFB",
          2: "#F3F4F6",
          3: "#E5E7EB",
          4: "#DEE2E6",
          5: "#CED4DA",
          6: "#CED4DA",
          7: "#CED4DA",
        },
        yellow: {
          DEFAULT: "#FBBF24",
          dark: "#F59D0B",
          dark2: "#D97706",
          light: "#FCD34D",
          light2: "#FDE68A",
          light3: "#FEF3C7",
          light4: "#FFFBEB",
        },
        orange: {
          DEFAULT: "#F27430",
          dark: "#E1580E",
          light: "#F8B490",
          light2: "#F8B490",
          light3: "#FBD5C0",
          light4: "#FDE5D8",
          light5: "#FFF0E9",
        },
        red: {
          DEFAULT: "#F23030",
          dark: "#E10E0E",
          light: "#F56060",
          light2: "#F89090",
          light3: "#FBC0C0",
          light4: "#FDD8D8",
          light5: "#FEEBEB",
          light6: "#FEF3F3",
        },
        pink: {
          DEFAULT: "#D345F9",
          dark: "#C814F6",
          light: "#DF76FA",
          light2: "#EAA7FC",
          light3: "#F6D8FE",
          light4: "#FCF1FE",
        },
        purple: {
          DEFAULT: "#8646F4",
          dark: "#6D28D9",
          dark2: "#5B2168",
          light: "#A78BFA",
          light2: "#C4B5FD",
          light3: "#DDD6FE",
          light4: "#EDE9FE",
          light5: "#F5F3FF",
        },
        blue: {
          DEFAULT: "#2D68F8",
          dark: "#1C3FB7",
          light: "#5475E5",
          light2: "#8099EC",
          light3: "#ADBCF2",
          light4: "#C3CEF6",
          light5: "#E1E8FF",
        },
        cyan: {
          DEFAULT: "#01A9DB",
          dark: "#0B76B7",
          light: "#18BFFF",
          light2: "#77D1F3",
          light3: "#D0F0FD",
        },
        teal: {
          DEFAULT: "#02AAA4",
          dark: "#06A09B",
          light: "#20D9D2",
          light2: "#72DDC3",
          light3: "#C2F5E9",
        },
        green: {
          DEFAULT: "#22AD5C",
          dark: "#1A8245",
          light: "#2CD673",
          light2: "#57DE8F",
          light3: "#82E6AC",
          light4: "#ACEFC8",
          light5: "#C2F3D6",
          light6: "#DAF8E6",
        },
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
